image: node:latest

before_script:
  - npm install
  - npm install dpl

stages:
  - staging

staging:
  type: deploy
  stage: staging
  image: node:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - master
