cache:
  paths:
    - node_modules/

stages:
  - staging

init:
  stage: init
  image: node:13.8.0
  script:
    - npm install

deploy_qa:
  image: node:13.8.0
  stage: staging
  script:
    - git push https://khan17171717@gmail.com:f6e0b4d6-429f-4139-aafb-930185dc9c0d@git.heroku.com/julia-qa.git HEAD:master
  environment:
    name: staging
    url: http://pg-front.herokuapp.com/
  only:
    - master
