export const TAKE_INFO_TABLE_SUCCESS ="TAKE_INFO_TABLE_SUCCESS";
export const TAKE_INFO_TABLE_ERROR ="TAKE_INFO_TABLE_ERROR";
export const TAKE_VALUE_INPUT ="TAKE_VALUE_INPUT"
export const TAKE_INFO_INPUT_SUCCESS ="TAKE_INFO_INPUT_SUCCESS";

